import { useState, useRef, type ChangeEvent } from 'react';
import { Upload, FileSpreadsheet, Loader2, CheckCircle, XCircle, AlertTriangle, ArrowLeft } from 'lucide-react';
import Modal from '@/components/Modal';
import { supabase } from '@/lib/supabaseClient';
import { useToast } from '@/hooks/useToast';
import { cn } from '@/utils/cn';
import {
  parseImportFile,
  validateRows,
  buildInsertPayload,
  type ImportRow,
  type ValidatedRow,
} from '@/utils/studentImportExport';

interface ImportStudentsModalProps {
  open: boolean;
  onClose: () => void;
  onSaved: () => void;
}

type Step = 'upload' | 'preview' | 'importing';

export default function ImportStudentsModal({ open, onClose, onSaved }: ImportStudentsModalProps) {
  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [step, setStep] = useState<Step>('upload');
  const [fileName, setFileName] = useState('');
  const [parseErrors, setParseErrors] = useState<string[]>([]);
  const [validatedRows, setValidatedRows] = useState<ValidatedRow[]>([]);
  const [importing, setImporting] = useState(false);
  const [totalSheetRows, setTotalSheetRows] = useState(0);

  const validCount = validatedRows.filter((r) => r.status === 'valid').length;
  const invalidCount = validatedRows.filter((r) => r.status === 'invalid').length;
  const duplicateCount = validatedRows.filter((r) => r.status === 'duplicate').length;

  function resetState() {
    setStep('upload');
    setFileName('');
    setParseErrors([]);
    setValidatedRows([]);
    setImporting(false);
    setTotalSheetRows(0);
    if (fileInputRef.current) fileInputRef.current.value = '';
  }

  function handleClose() {
    resetState();
    onClose();
  }

  // ── Step 1: Parse file ───────────────────────────────────────
  async function handleFileSelect(e: ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setParseErrors([]);
    setValidatedRows([]);

    // Parse the file
    const result = await parseImportFile(file);
    setTotalSheetRows(result.totalSheetRows);

    if (result.parseErrors.length > 0 && result.rows.length === 0) {
      setParseErrors(result.parseErrors);
      return;
    }
    if (result.parseErrors.length > 0) {
      setParseErrors(result.parseErrors);
    }

    if (result.rows.length === 0) {
      setParseErrors(['No data rows found in the file.']);
      return;
    }

    // Fetch existing student IDs for duplicate detection
    const { data: existingStudents } = await supabase
      .from('students')
      .select('student_id');
    const existingIds = new Set<string>(
      (existingStudents ?? [])
        .map((s) => s.student_id?.toUpperCase())
        .filter((id): id is string => !!id),
    );

    // Validate rows
    const validated = await validateRows(result.rows, existingIds);
    setValidatedRows(validated);
    setStep('preview');
  }

  // ── Step 2: Import valid rows ────────────────────────────────
  async function handleImport() {
    const validRows = validatedRows.filter((r) => r.status === 'valid');
    if (validRows.length === 0) return;

    setStep('importing');
    setImporting(true);

    let successCount = 0;
    let failCount = 0;
    const failMessages: string[] = [];

    for (const vr of validRows) {
      const payload = buildInsertPayload(vr.row, vr.autoGeneratedId);
      const { error } = await supabase.from('students').insert(payload);
      if (error) {
        failCount++;
        const name = vr.row.full_name || vr.autoGeneratedId || `Row ${vr.row.student_id ?? '?'}`;
        failMessages.push(`${name}: ${error.message}`);
      } else {
        successCount++;
      }
    }

    setImporting(false);

    if (successCount > 0) {
      toast(`${successCount} student${successCount !== 1 ? 's' : ''} imported successfully`, 'success');
    }
    if (failCount > 0) {
      toast(`${failCount} row${failCount !== 1 ? 's' : ''} failed: ${failMessages[0]}`, 'error');
    }

    onSaved();
    handleClose();
  }

  return (
    <Modal
      open={open}
      onClose={handleClose}
      title="Import Students"
      description="Upload an Excel (.xlsx) or CSV file with student data"
      size="xl"
    >
      {/* ── Step: Upload ─────────────────────────────────────── */}
      {step === 'upload' && (
        <div className="space-y-4">
          {parseErrors.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 space-y-1">
              {parseErrors.map((err, i) => (
                <p key={i} className="text-sm text-red-700 flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4 flex-shrink-0" />
                  {err}
                </p>
              ))}
            </div>
          )}

          <div className="border-2 border-dashed border-slate-300 rounded-xl p-8 text-center hover:border-slate-400 transition">
            <Upload className="h-10 w-10 text-slate-400 mx-auto mb-3" />
            <p className="text-sm font-medium text-slate-700 mb-1">
              Select a file to import
            </p>
            <p className="text-xs text-slate-400 mb-4">
              Supports .xlsx and .csv files. Maximum 1,000 rows.
            </p>
            <input
              ref={fileInputRef}
              type="file"
              accept=".xlsx,.csv"
              onChange={handleFileSelect}
              className="hidden"
              id="import-file-input"
            />
            <label
              htmlFor="import-file-input"
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-white bg-slate-900 hover:bg-slate-800 transition cursor-pointer"
            >
              <FileSpreadsheet className="h-4 w-4" />
              Choose File
            </label>
          </div>

          <div className="bg-slate-50 border border-slate-200 rounded-lg p-4">
            <p className="text-xs font-semibold text-slate-600 mb-2">Expected column headers:</p>
            <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500">
              <span>Student ID</span>
              <span>Student Name *</span>
              <span>Mobile Number</span>
              <span>Email</span>
              <span>DOB</span>
              <span>Gender</span>
              <span>Address</span>
              <span>Admission Date *</span>
              <span>Parent/Guardian Name</span>
              <span>Parent/Guardian Mobile</span>
              <span>Relationship</span>
            </div>
            <p className="text-xs text-slate-400 mt-2">* Required fields. Student ID is auto-generated if left empty.</p>
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={handleClose}
              className="px-4 py-2 rounded-lg text-sm font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 transition"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* ── Step: Preview ────────────────────────────────────── */}
      {step === 'preview' && (
        <div className="space-y-4">
          {/* Summary bar */}
          <div className="flex flex-wrap items-center gap-3">
            <span className="text-sm text-slate-600">
              <span className="font-medium text-slate-800">{fileName}</span>
              <span className="text-slate-400 ml-2">({totalSheetRows} rows in file)</span>
            </span>
            <div className="flex gap-2 ml-auto">
              <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-emerald-50 text-emerald-700">
                <CheckCircle className="h-3 w-3" /> {validCount} valid
              </span>
              <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-red-50 text-red-700">
                <XCircle className="h-3 w-3" /> {invalidCount} errors
              </span>
              <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-amber-50 text-amber-700">
                <AlertTriangle className="h-3 w-3" /> {duplicateCount} duplicates
              </span>
            </div>
          </div>

          {parseErrors.length > 0 && (
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 space-y-1">
              {parseErrors.map((err, i) => (
                <p key={i} className="text-xs text-amber-700">{err}</p>
              ))}
            </div>
          )}

          {/* Preview table */}
          <div className="border border-slate-200 rounded-lg overflow-hidden">
            <div className="overflow-x-auto max-h-80 overflow-y-auto">
              <table className="w-full text-xs">
                <thead className="sticky top-0 z-10">
                  <tr className="bg-slate-100 border-b border-slate-200">
                    <th className="text-left px-3 py-2 font-medium text-slate-600 w-8">#</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600">Status</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600">Student ID</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600">Name</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600 hidden sm:table-cell">Mobile</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600 hidden md:table-cell">Email</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600 hidden lg:table-cell">DOB</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600 hidden lg:table-cell">Admission</th>
                    <th className="text-left px-3 py-2 font-medium text-slate-600">Errors</th>
                  </tr>
                </thead>
                <tbody>
                  {validatedRows.map((vr, idx) => (
                    <tr
                      key={idx}
                      className={cn(
                        'border-b border-slate-100',
                        vr.status === 'valid' && 'bg-emerald-50/40',
                        vr.status === 'invalid' && 'bg-red-50/40',
                        vr.status === 'duplicate' && 'bg-amber-50/40',
                      )}
                    >
                      <td className="px-3 py-1.5 text-slate-400">{idx + 1}</td>
                      <td className="px-3 py-1.5">
                        {vr.status === 'valid' && (
                          <span className="inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium bg-emerald-100 text-emerald-700">Valid</span>
                        )}
                        {vr.status === 'invalid' && (
                          <span className="inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium bg-red-100 text-red-700">Error</span>
                        )}
                        {vr.status === 'duplicate' && (
                          <span className="inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium bg-amber-100 text-amber-700">Duplicate</span>
                        )}
                      </td>
                      <td className="px-3 py-1.5 text-slate-700 font-mono">
                        {vr.row.student_id ?? vr.autoGeneratedId ?? '—'}
                        {vr.autoGeneratedId && (
                          <span className="ml-1 text-[10px] text-sky-500">(auto)</span>
                        )}
                      </td>
                      <td className="px-3 py-1.5 text-slate-800 font-medium max-w-[150px] truncate">
                        {vr.row.full_name || '—'}
                      </td>
                      <td className="px-3 py-1.5 text-slate-600 hidden sm:table-cell">{vr.row.mobile_number || '—'}</td>
                      <td className="px-3 py-1.5 text-slate-600 hidden md:table-cell max-w-[130px] truncate">{vr.row.email || '—'}</td>
                      <td className="px-3 py-1.5 text-slate-600 hidden lg:table-cell">{vr.row.date_of_birth || '—'}</td>
                      <td className="px-3 py-1.5 text-slate-600 hidden lg:table-cell">{vr.row.admission_date || '—'}</td>
                      <td className="px-3 py-1.5 text-red-600 max-w-[200px]">
                        {vr.errors.length > 0 && (
                          <span className="text-[10px] leading-tight">{vr.errors.join('; ')}</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex justify-between items-center pt-2">
            <button
              type="button"
              onClick={() => {
                setStep('upload');
                setValidatedRows([]);
                setParseErrors([]);
                if (fileInputRef.current) fileInputRef.current.value = '';
              }}
              className="flex items-center gap-1 px-3 py-2 rounded-lg text-sm font-medium text-slate-600 hover:text-slate-900 transition"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </button>
            <div className="flex gap-3">
              <button
                type="button"
                onClick={handleClose}
                className="px-4 py-2 rounded-lg text-sm font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 transition"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleImport}
                disabled={validCount === 0}
                className="px-4 py-2 rounded-lg text-sm font-medium text-white bg-slate-900 hover:bg-slate-800 transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                <Upload className="h-4 w-4" />
                Import {validCount} Valid Row{validCount !== 1 ? 's' : ''}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Step: Importing ──────────────────────────────────── */}
      {step === 'importing' && (
        <div className="flex flex-col items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-slate-400 mb-4" />
          <p className="text-sm font-medium text-slate-700">Importing students...</p>
          <p className="text-xs text-slate-400 mt-1">Please do not close this window</p>
        </div>
      )}
    </Modal>
  );
}
