import * as XLSX from 'xlsx';
import type { Student, ParentRelationship } from '@/types/database';

// ── Column header mapping (file header → DB column) ──────────────
const HEADER_MAP: Record<string, keyof ImportRow> = {
  'student id': 'student_id',
  'student_id': 'student_id',
  'studentid': 'student_id',
  'student name': 'full_name',
  'full_name': 'full_name',
  'fullname': 'full_name',
  'name': 'full_name',
  'mobile number': 'mobile_number',
  'mobile_number': 'mobile_number',
  'mobile': 'mobile_number',
  'phone': 'mobile_number',
  'email': 'email',
  'e-mail': 'email',
  'dob': 'date_of_birth',
  'date of birth': 'date_of_birth',
  'date_of_birth': 'date_of_birth',
  'birthday': 'date_of_birth',
  'gender': 'gender',
  'sex': 'gender',
  'address': 'address',
  'admission date': 'admission_date',
  'admission_date': 'admission_date',
  'admissiondate': 'admission_date',
  'admission': 'admission_date',
  'parent/guardian name': 'parent_name',
  'parent name': 'parent_name',
  'parent_name': 'parent_name',
  'guardian name': 'parent_name',
  'parent/guardian mobile': 'parent_mobile',
  'parent mobile': 'parent_mobile',
  'parent_mobile': 'parent_mobile',
  'guardian mobile': 'parent_mobile',
  'relationship': 'parent_relationship',
  'parent relationship': 'parent_relationship',
  'parent_relationship': 'parent_relationship',
};

const ALLOWED_GENDERS = ['Male', 'Female', 'Other'];
const ALLOWED_RELATIONSHIPS: ParentRelationship[] = ['Father', 'Mother', 'Guardian', 'Other'];
const MAX_ROWS = 1000;

// ── Types ────────────────────────────────────────────────────────
export interface ImportRow {
  student_id: string | null;
  full_name: string;
  mobile_number: string | null;
  email: string | null;
  date_of_birth: string | null;
  gender: string | null;
  address: string | null;
  admission_date: string | null;
  parent_name: string | null;
  parent_mobile: string | null;
  parent_relationship: string | null;
}

export interface ValidatedRow {
  row: ImportRow;
  status: 'valid' | 'invalid' | 'duplicate';
  errors: string[];
  autoGeneratedId: string | null;
}

export interface ParseResult {
  rows: ImportRow[];
  parseErrors: string[];
  totalSheetRows: number;
}

// ── Helpers ──────────────────────────────────────────────────────
function emptyRow(): ImportRow {
  return {
    student_id: null,
    full_name: '',
    mobile_number: null,
    email: null,
    date_of_birth: null,
    gender: null,
    address: null,
    admission_date: null,
    parent_name: null,
    parent_mobile: null,
    parent_relationship: null,
  };
}

function isBlank(val: string | null | undefined): boolean {
  return val == null || String(val).trim() === '';
}

function toStr(val: unknown): string {
  if (val == null) return '';
  if (val instanceof Date) {
    const y = val.getFullYear();
    const m = String(val.getMonth() + 1).padStart(2, '0');
    const d = String(val.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
  }
  return String(val).trim();
}

function normalizeDate(raw: string): string | null {
  if (!raw) return null;
  // Already YYYY-MM-DD
  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw;
  // DD/MM/YYYY or DD-MM-YYYY
  const dmy = raw.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);
  if (dmy) {
    const [, dd, mm, yyyy] = dmy;
    return `${yyyy}-${mm.padStart(2, '0')}-${dd.padStart(2, '0')}`;
  }
  // MM/DD/YYYY (US format) — try as fallback
  const parsed = new Date(raw);
  if (!isNaN(parsed.getTime())) {
    const y = parsed.getFullYear();
    const m = String(parsed.getMonth() + 1).padStart(2, '0');
    const d = String(parsed.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
  }
  return null;
}

function isValidDate(dateStr: string): boolean {
  const d = new Date(dateStr + 'T00:00:00');
  return !isNaN(d.getTime());
}

function isFutureDate(dateStr: string): boolean {
  const d = new Date(dateStr + 'T00:00:00');
  const today = new Date();
  today.setHours(23, 59, 59, 999);
  return d > today;
}

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function isRowCompletelyEmpty(row: ImportRow): boolean {
  return Object.values(row).every((v) => isBlank(v));
}

// ── Parse file ───────────────────────────────────────────────────
export function parseImportFile(file: File): Promise<ParseResult> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    const parseErrors: string[] = [];

    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target?.result as ArrayBuffer);
        const wb = XLSX.read(data, { type: 'array', cellDates: true });
        const ws = wb.Sheets[wb.SheetNames[0]];
        if (!ws) {
          resolve({ rows: [], parseErrors: ['File appears to be empty or corrupt.'], totalSheetRows: 0 });
          return;
        }

        const jsonRows = XLSX.utils.sheet_to_json<Record<string, unknown>>(ws, { defval: '' });
        const totalSheetRows = jsonRows.length;

        if (totalSheetRows === 0) {
          resolve({ rows: [], parseErrors: ['No data rows found in the file.'], totalSheetRows: 0 });
          return;
        }

        if (totalSheetRows > MAX_ROWS) {
          resolve({
            rows: [],
            parseErrors: [`File has ${totalSheetRows} rows. Maximum allowed is ${MAX_ROWS}. Please reduce the file size.`],
            totalSheetRows,
          });
          return;
        }

        // Map headers
        const rawHeaders = Object.keys(jsonRows[0] ?? {});
        const headerMapping: Record<string, keyof ImportRow> = {};
        const unmappedHeaders: string[] = [];

        for (const h of rawHeaders) {
          const normalized = h.trim().toLowerCase();
          const mapped = HEADER_MAP[normalized];
          if (mapped) {
            headerMapping[h] = mapped;
          } else {
            unmappedHeaders.push(h);
          }
        }

        if (unmappedHeaders.length > 0) {
          parseErrors.push(`Unrecognized columns (ignored): ${unmappedHeaders.join(', ')}`);
        }

        // Check required mapped columns exist
        const mappedFields = new Set(Object.values(headerMapping));
        if (!mappedFields.has('full_name')) {
          parseErrors.push('Missing required column: Student Name');
        }

        // Parse rows
        const rows: ImportRow[] = [];
        for (let i = 0; i < jsonRows.length; i++) {
          const raw = jsonRows[i];
          const row = emptyRow();

          for (const [fileHeader, field] of Object.entries(headerMapping)) {
            const val = toStr(raw[fileHeader]);
            (row as unknown as Record<string, string | null>)[field] = val || null;
          }

          // Skip completely empty rows
          if (isRowCompletelyEmpty(row)) continue;

          rows.push(row);
        }

        resolve({ rows, parseErrors, totalSheetRows });
      } catch {
        resolve({ rows: [], parseErrors: ['Failed to parse file. Please check the format and try again.'], totalSheetRows: 0 });
      }
    };

    reader.onerror = () => {
      resolve({ rows: [], parseErrors: ['Failed to read the file.'], totalSheetRows: 0 });
    };

    reader.readAsArrayBuffer(file);
  });
}

// ── Validate rows ────────────────────────────────────────────────
export async function validateRows(
  rows: ImportRow[],
  existingStudentIds: Set<string>,
): Promise<ValidatedRow[]> {
  // First pass: determine which rows need auto-generated IDs
  // and find the starting number for generation
  let maxNum = 0;
  for (const sid of existingStudentIds) {
    const match = sid.match(/^ST(\d+)$/);
    if (match) {
      const n = parseInt(match[1], 10);
      if (n > maxNum) maxNum = n;
    }
  }

  // Track IDs seen within this file to detect in-file duplicates
  const fileIds = new Map<string, number[]>(); // id → row indices
  for (let i = 0; i < rows.length; i++) {
    const sid = rows[i].student_id?.trim().toUpperCase() ?? '';
    if (sid) {
      if (!fileIds.has(sid)) fileIds.set(sid, []);
      fileIds.get(sid)!.push(i);
    }
  }

  let nextGenNum = maxNum + 1;
  const results: ValidatedRow[] = [];

  for (let i = 0; i < rows.length; i++) {
    const row = { ...rows[i] };
    const errors: string[] = [];
    let autoGeneratedId: string | null = null;

    // Normalize student_id
    const rawId = row.student_id?.trim().toUpperCase() ?? '';
    const sid = rawId || null;

    // ── Student ID handling ──
    if (sid) {
      // Check if exists in DB
      if (existingStudentIds.has(sid)) {
        errors.push(`Student ID "${sid}" already exists in the database`);
      }
      // Check if duplicated within the file
      const indices = fileIds.get(sid) ?? [];
      if (indices.length > 1 && indices[0] !== i) {
        errors.push(`Student ID "${sid}" is duplicated in the upload file`);
      }
    } else {
      // Auto-generate
      autoGeneratedId = `ST${String(nextGenNum).padStart(3, '0')}`;
      nextGenNum++;
    }

    // ── Required field: full_name ──
    if (isBlank(row.full_name)) {
      errors.push('Student Name is required');
    }

    // ── Required field: admission_date ──
    if (isBlank(row.admission_date)) {
      errors.push('Admission Date is required');
    } else {
      const normalized = normalizeDate(row.admission_date!);
      if (!normalized) {
        errors.push('Invalid Admission Date format');
      } else if (!isValidDate(normalized)) {
        errors.push('Invalid Admission Date');
      } else if (isFutureDate(normalized)) {
        errors.push('Admission Date cannot be in the future');
      }
      row.admission_date = normalized;
    }

    // ── Optional: email ──
    if (!isBlank(row.email) && !isValidEmail(row.email!)) {
      errors.push('Invalid email format');
    }

    // ── Optional: DOB ──
    if (!isBlank(row.date_of_birth)) {
      const normalized = normalizeDate(row.date_of_birth!);
      if (!normalized) {
        errors.push('Invalid DOB format');
      } else if (!isValidDate(normalized)) {
        errors.push('Invalid DOB');
      } else if (isFutureDate(normalized)) {
        errors.push('Date of birth cannot be in the future');
      }
      row.date_of_birth = normalized;
    }

    // ── Optional: gender ──
    if (!isBlank(row.gender)) {
      const g = row.gender!.charAt(0).toUpperCase() + row.gender!.slice(1).toLowerCase();
      if (!ALLOWED_GENDERS.includes(g)) {
        errors.push(`Gender must be one of: ${ALLOWED_GENDERS.join(', ')}`);
      } else {
        row.gender = g;
      }
    }

    // ── Optional: parent_relationship ──
    if (!isBlank(row.parent_relationship)) {
      const r = row.parent_relationship!.charAt(0).toUpperCase() + row.parent_relationship!.slice(1).toLowerCase();
      if (!ALLOWED_RELATIONSHIPS.includes(r as ParentRelationship)) {
        errors.push(`Relationship must be one of: ${ALLOWED_RELATIONSHIPS.join(', ')}`);
      } else {
        row.parent_relationship = r;
      }
    }

    // Determine status
    let status: ValidatedRow['status'] = 'valid';
    if (errors.length > 0) {
      status = 'invalid';
    } else if (!sid) {
      // Valid with auto-generated ID
      status = 'valid';
    } else if (existingStudentIds.has(sid)) {
      status = 'duplicate';
    } else {
      const indices = fileIds.get(sid) ?? [];
      if (indices.length > 1 && indices[0] !== i) {
        status = 'duplicate';
      }
    }

    // Store normalized student_id back
    row.student_id = sid;

    results.push({ row, status, errors, autoGeneratedId });
  }

  return results;
}

// ── Build Supabase payload ───────────────────────────────────────
export function buildInsertPayload(row: ImportRow, autoGeneratedId: string | null) {
  return {
    student_id: row.student_id ?? autoGeneratedId,
    full_name: row.full_name.trim(),
    mobile_number: row.mobile_number?.trim() || null,
    email: row.email?.trim() || null,
    date_of_birth: row.date_of_birth || null,
    gender: (row.gender || null) as Student['gender'],
    address: row.address?.trim() || null,
    admission_date: row.admission_date || null,
    parent_name: row.parent_name?.trim() || null,
    parent_mobile: row.parent_mobile?.trim() || null,
    parent_relationship: (row.parent_relationship || null) as Student['parent_relationship'],
    status: 'Active' as const,
  };
}

// ── Export ───────────────────────────────────────────────────────
const EXPORT_HEADERS = [
  'Student ID',
  'Student Name',
  'Mobile Number',
  'Email',
  'DOB',
  'Gender',
  'Address',
  'Admission Date',
  'Parent/Guardian Name',
  'Parent/Guardian Mobile',
  'Relationship',
];

export function exportStudentsToXlsx(students: Student[]): void {
  const data = students.map((s) => [
    s.student_id ?? '',
    s.full_name,
    s.mobile_number ?? '',
    s.email ?? '',
    s.date_of_birth ?? '',
    s.gender ?? '',
    s.address ?? '',
    s.admission_date ?? '',
    s.parent_name ?? '',
    s.parent_mobile ?? '',
    s.parent_relationship ?? '',
  ]);

  const ws = XLSX.utils.aoa_to_sheet([EXPORT_HEADERS, ...data]);

  // Set column widths for readability
  ws['!cols'] = [
    { wch: 12 }, // Student ID
    { wch: 25 }, // Name
    { wch: 15 }, // Mobile
    { wch: 25 }, // Email
    { wch: 12 }, // DOB
    { wch: 8 },  // Gender
    { wch: 30 }, // Address
    { wch: 14 }, // Admission Date
    { wch: 22 }, // Parent Name
    { wch: 15 }, // Parent Mobile
    { wch: 14 }, // Relationship
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Students');

  const today = new Date().toISOString().split('T')[0];
  XLSX.writeFile(wb, `students_export_${today}.xlsx`);
}
