/*
# Computer Class Management System - Foundation Schema

## Overview
Creates the complete database foundation for a Computer Training Institute
management system. This migration establishes all 8 core tables with proper
relationships, constraints, and security so that future steps can add
Students, Courses, Enrollments, Attendance, Fees, Exams, and Certificates
modules WITHOUT rebuilding the database.

## 1. New Tables

### profiles
- `id` (uuid, PK, references auth.users) — one row per authenticated admin user
- `email` (text, unique) — admin email
- `full_name` (text) — admin display name
- `created_at` / `updated_at` (timestamptz)

### students
- `id` (uuid, PK)
- `student_id` (text, UNIQUE) — human-readable code ST001, ST002, ...
- `full_name` (text, not null)
- `mobile_number` (text)
- `email` (text)
- `date_of_birth` (date)
- `gender` (text) — Male / Female / Other
- `address` (text)
- `admission_date` (date)
- `status` (text, default 'Active') — Active / Inactive
- `created_at` / `updated_at` (timestamptz)

### courses
- `id` (uuid, PK)
- `course_code` (text, UNIQUE) — human-readable code
- `course_name` (text, not null)
- `default_fees` (numeric, default 0) — stored separately from student-specific fees
- `duration` (text) — e.g. "3 months"
- `status` (text, default 'Active') — Active / Inactive
- `created_at` / `updated_at` (timestamptz)

### enrollments
- `id` (uuid, PK)
- `student_id` (uuid, FK -> students.id ON DELETE CASCADE)
- `course_id` (uuid, FK -> courses.id ON DELETE RESTRICT)
- `batch_name` (text)
- `joining_date` (date)
- `default_fees_snapshot` (numeric) — frozen copy of course default_fees at enrollment time
- `discount` (numeric, default 0)
- `final_fees` (numeric) — snapshot - discount
- `status` (text, default 'Active') — Active / Exam Pending / Completed / Inactive
- `created_at` / `updated_at` (timestamptz)

### attendance
- `id` (uuid, PK)
- `enrollment_id` (uuid, FK -> enrollments.id ON DELETE CASCADE)
- `attendance_date` (date, not null)
- `status` (text) — Present / Absent
- `remarks` (text)
- `created_at` / `updated_at` (timestamptz)
- UNIQUE (enrollment_id, attendance_date) — prevents duplicate daily attendance

### fee_payments
- `id` (uuid, PK)
- `enrollment_id` (uuid, FK -> enrollments.id ON DELETE CASCADE)
- `payment_date` (date, not null)
- `receipt_number` (text)
- `amount` (numeric, not null)
- `payment_mode` (text) — Cash / UPI / Bank / Other
- `remarks` (text)
- `created_at` (timestamptz)
- Each payment is a separate transaction; never overwritten

### exams
- `id` (uuid, PK)
- `enrollment_id` (uuid, FK -> enrollments.id ON DELETE CASCADE)
- `exam_date` (date)
- `exam_name` (text)
- `result` (text) — Pass / Fail / Pending
- `remarks` (text)
- `created_at` / `updated_at` (timestamptz)

### certificates
- `id` (uuid, PK)
- `enrollment_id` (uuid, FK -> enrollments.id ON DELETE CASCADE)
- `certificate_number` (text, UNIQUE)
- `certificate_month` (text) — e.g. "2026-08"
- `status` (text) — Ready / Issued
- `issue_date` (date)
- `received_by_student` (boolean, default false)
- `created_at` / `updated_at` (timestamptz)

## 2. Relationships
- students 1:N enrollments N:1 courses
- enrollments 1:N attendance
- enrollments 1:N fee_payments
- enrollments 1:N exams
- enrollments 1:N certificates

## 3. Constraints
- students.student_id UNIQUE
- courses.course_code UNIQUE
- certificates.certificate_number UNIQUE
- attendance UNIQUE (enrollment_id, attendance_date)
- All foreign keys enforced
- Non-null where marked

## 4. Security (RLS)
- All tables have RLS ENABLED.
- This app HAS a sign-in screen (admin login), so policies are scoped
  TO authenticated with ownership via auth.uid().
- profiles: each admin can read/update their own profile row.
- Business tables (students, courses, enrollments, attendance,
  fee_payments, exams, certificates): any authenticated admin can
  perform CRUD — the app is a single shared admin workspace, so all
  authenticated admins manage the same institute data.
- Unauthenticated users get NO access to any business table.
- 4 separate policies per table (SELECT/INSERT/UPDATE/DELETE), no FOR ALL.

## 5. Important Notes
1. No sample/fake data is inserted. All tables start empty.
2. Student ID (ST001 format) will be generated by application code in a
   future step, not by the database.
3. Enrollment stores a frozen snapshot of course default_fees so that
   later course fee changes do NOT retroactively alter existing enrollments.
4. Paid amount and balance are NOT stored — they will be calculated from
   fee_payments in a future step to avoid inconsistency.
5. updated_at columns auto-refresh via triggers.
*/

-- ============================================================
-- updated_at helper function (idempotent)
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ============================================================
-- profiles
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  full_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_profile" ON public.profiles;
CREATE POLICY "select_own_profile" ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "insert_own_profile" ON public.profiles;
CREATE POLICY "insert_own_profile" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "update_own_profile" ON public.profiles;
CREATE POLICY "update_own_profile" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP TRIGGER IF EXISTS profiles_set_updated_at ON public.profiles;
CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- students
-- ============================================================
CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id text UNIQUE,
  full_name text NOT NULL,
  mobile_number text,
  email text,
  date_of_birth date,
  gender text CHECK (gender IN ('Male', 'Female', 'Other')),
  address text,
  admission_date date,
  status text NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_students" ON public.students;
CREATE POLICY "select_students" ON public.students
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_students" ON public.students;
CREATE POLICY "insert_students" ON public.students
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_students" ON public.students;
CREATE POLICY "update_students" ON public.students
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_students" ON public.students;
CREATE POLICY "delete_students" ON public.students
  FOR DELETE TO authenticated USING (true);

DROP TRIGGER IF EXISTS students_set_updated_at ON public.students;
CREATE TRIGGER students_set_updated_at
  BEFORE UPDATE ON public.students
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- courses
-- ============================================================
CREATE TABLE IF NOT EXISTS public.courses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_code text UNIQUE,
  course_name text NOT NULL,
  default_fees numeric(12,2) NOT NULL DEFAULT 0,
  duration text,
  status text NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_courses" ON public.courses;
CREATE POLICY "select_courses" ON public.courses
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_courses" ON public.courses;
CREATE POLICY "insert_courses" ON public.courses
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_courses" ON public.courses;
CREATE POLICY "update_courses" ON public.courses
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_courses" ON public.courses;
CREATE POLICY "delete_courses" ON public.courses
  FOR DELETE TO authenticated USING (true);

DROP TRIGGER IF EXISTS courses_set_updated_at ON public.courses;
CREATE TRIGGER courses_set_updated_at
  BEFORE UPDATE ON public.courses
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- enrollments
-- ============================================================
CREATE TABLE IF NOT EXISTS public.enrollments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  course_id uuid NOT NULL REFERENCES public.courses(id) ON DELETE RESTRICT,
  batch_name text,
  joining_date date,
  default_fees_snapshot numeric(12,2) NOT NULL DEFAULT 0,
  discount numeric(12,2) NOT NULL DEFAULT 0,
  final_fees numeric(12,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Exam Pending', 'Completed', 'Inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_enrollments" ON public.enrollments;
CREATE POLICY "select_enrollments" ON public.enrollments
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_enrollments" ON public.enrollments;
CREATE POLICY "insert_enrollments" ON public.enrollments
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_enrollments" ON public.enrollments;
CREATE POLICY "update_enrollments" ON public.enrollments
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_enrollments" ON public.enrollments;
CREATE POLICY "delete_enrollments" ON public.enrollments
  FOR DELETE TO authenticated USING (true);

DROP TRIGGER IF EXISTS enrollments_set_updated_at ON public.enrollments;
CREATE TRIGGER enrollments_set_updated_at
  BEFORE UPDATE ON public.enrollments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- attendance
-- ============================================================
CREATE TABLE IF NOT EXISTS public.attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL REFERENCES public.enrollments(id) ON DELETE CASCADE,
  attendance_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('Present', 'Absent')),
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (enrollment_id, attendance_date)
);

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_attendance" ON public.attendance;
CREATE POLICY "select_attendance" ON public.attendance
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_attendance" ON public.attendance;
CREATE POLICY "insert_attendance" ON public.attendance
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_attendance" ON public.attendance;
CREATE POLICY "update_attendance" ON public.attendance
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_attendance" ON public.attendance;
CREATE POLICY "delete_attendance" ON public.attendance
  FOR DELETE TO authenticated USING (true);

DROP TRIGGER IF EXISTS attendance_set_updated_at ON public.attendance;
CREATE TRIGGER attendance_set_updated_at
  BEFORE UPDATE ON public.attendance
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- fee_payments
-- ============================================================
CREATE TABLE IF NOT EXISTS public.fee_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL REFERENCES public.enrollments(id) ON DELETE CASCADE,
  payment_date date NOT NULL,
  receipt_number text,
  amount numeric(12,2) NOT NULL,
  payment_mode text CHECK (payment_mode IN ('Cash', 'UPI', 'Bank', 'Other')),
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.fee_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_fee_payments" ON public.fee_payments;
CREATE POLICY "select_fee_payments" ON public.fee_payments
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_fee_payments" ON public.fee_payments;
CREATE POLICY "insert_fee_payments" ON public.fee_payments
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_fee_payments" ON public.fee_payments;
CREATE POLICY "update_fee_payments" ON public.fee_payments
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_fee_payments" ON public.fee_payments;
CREATE POLICY "delete_fee_payments" ON public.fee_payments
  FOR DELETE TO authenticated USING (true);

-- ============================================================
-- exams
-- ============================================================
CREATE TABLE IF NOT EXISTS public.exams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL REFERENCES public.enrollments(id) ON DELETE CASCADE,
  exam_date date,
  exam_name text,
  result text CHECK (result IN ('Pass', 'Fail', 'Pending')),
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_exams" ON public.exams;
CREATE POLICY "select_exams" ON public.exams
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_exams" ON public.exams;
CREATE POLICY "insert_exams" ON public.exams
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_exams" ON public.exams;
CREATE POLICY "update_exams" ON public.exams
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_exams" ON public.exams;
CREATE POLICY "delete_exams" ON public.exams
  FOR DELETE TO authenticated USING (true);

DROP TRIGGER IF EXISTS exams_set_updated_at ON public.exams;
CREATE TRIGGER exams_set_updated_at
  BEFORE UPDATE ON public.exams
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- certificates
-- ============================================================
CREATE TABLE IF NOT EXISTS public.certificates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL REFERENCES public.enrollments(id) ON DELETE CASCADE,
  certificate_number text UNIQUE,
  certificate_month text,
  status text NOT NULL DEFAULT 'Ready' CHECK (status IN ('Ready', 'Issued')),
  issue_date date,
  received_by_student boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_certificates" ON public.certificates;
CREATE POLICY "select_certificates" ON public.certificates
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_certificates" ON public.certificates;
CREATE POLICY "insert_certificates" ON public.certificates
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_certificates" ON public.certificates;
CREATE POLICY "update_certificates" ON public.certificates
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_certificates" ON public.certificates;
CREATE POLICY "delete_certificates" ON public.certificates
  FOR DELETE TO authenticated USING (true);

DROP TRIGGER IF EXISTS certificates_set_updated_at ON public.certificates;
CREATE TRIGGER certificates_set_updated_at
  BEFORE UPDATE ON public.certificates
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- Indexes for frequently queried columns
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_enrollments_student_id ON public.enrollments(student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_course_id ON public.enrollments(course_id);
CREATE INDEX IF NOT EXISTS idx_attendance_enrollment_id ON public.attendance(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance(attendance_date);
CREATE INDEX IF NOT EXISTS idx_fee_payments_enrollment_id ON public.fee_payments(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_exams_enrollment_id ON public.exams(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_certificates_enrollment_id ON public.certificates(enrollment_id);
